language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-23
    - extra-android-support
    - extra-google-m2repository
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-c81a61d9
    - android-sdk-license-5be876d5
    - android-sdk-license-.+
    - google-gdk-license-.+
    
branches:
  only:
    - master
    - travis
    
before_script: 
    - cd demo/demo

script: 
    - ./gradlew build --stacktrace
