language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-23
    - extra-android-support
  licenses:    
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license.+'
    
branches:
  only:
    - master
    - travis
    
before_script: 
    - cd demo/demo

script: 
    - ./gradlew build --stacktrace
