language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-21.1.2
    - android-23

before_script:
  # - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
  # - emulator -avd test -no-skin -no-audio -no-window &
  # - adb wait-for-device
  
script: ./gradlew build
